services:
  - type: web
    name: knowledge-hub-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: DB_KEY
      - key: API_KEY
      - key: BASE_URL
        value: "https://gen.ai.kku.ac.th/api/v1"
      - key: LOCAL_API_URL
        value: "http://127.0.0.1:8000"